Numpy

A numpy array is a collection of homogenous values.

All of the same type.
Indexed by a tuple of nonnegative integers.
The number of dimensions is the rank of the array.
The shape of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
# 1D array
import numpy as np
a = np.array([15,25,14,78,96])
a
type(a)

print(a)
a.dtype
np.size(a)


[15 25 14 78 96]


5

In [2]:
# 1D array
import numpy as np
a = np.array([15,25,14,78,'A'])
a
type(a)

print(a)
a.dtype
np.size(a)

['15' '25' '14' '78' 'A']


5

In [3]:
# changing the datatype
a.dtype
a = np.array([15,25,14,78,96],dtype = "float")
print(a)
a.dtype

[15. 25. 14. 78. 96.]


dtype('float64')

In [4]:
# Creating the sequence of numbers using **arange** function

a = np.arange(10) 
print(a)
# b = np.arange(start = 20,stop = 30)  #OR
b = np.arange(20,30)
print(b)

c = np.arange(20,30,-3)       #arange(start,stop,stepsize)  
print(c) 

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29]
[]


In [5]:
## Indexing [starts from 0]
print(b)
print(b[0])
print(b[5])
print(b[-1])

b[:5]  # first five elements

[20 21 22 23 24 25 26 27 28 29]
20
25
29


array([20, 21, 22, 23, 24])

In [6]:
# One dimentional sub arrays
d = np.arange(10)
print(d)

print(d[:5])  # first five elements
print(d[5:])  # elements after index 5
print(d[4:7])  # middle sub-array 4 to 6

# Getting a little more fancy [startindex:endindex:stepsize]

print(d[::])  # every alternate element
print(d[1::2])  # every alternate element, starting at index 1
print(d[::-1]) # all elements, reversed
print(d[5::-2])  # reversed every other from index 5 

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [7]:
## Multi Dimentional Array
# e = np.array([[1, 2, 3], [4, 5, 6]], 'i4')
e = np.array([[1, 2, 3,4], [4, 5, 6,7],[8,9,1,2]], dtype = np.int32)
# e = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(e)
print(e)
#Slicing and sub array
f = e[:2, :3] ## first two rows and three columns
print(f)
# #subarray dimensions can even be reversed together:
print(f[::-1, ::-1])
f[::, ::-1]
f[::-1, ::]

[[1 2 3 4]
 [4 5 6 7]
 [8 9 1 2]]
[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


array([[4, 5, 6],
       [1, 2, 3]])

In [8]:
#Accessing array rows and columns

print(f)
print(f[:, 0])  # first column of array
print(f[0, :])  # first row of array
print(f[0])  # equivalent to array[0, :]

[[1 2 3]
 [4 5 6]]
[1 4]
[1 2 3]
[1 2 3]


In [9]:
# Reshaping the arrays 
f = np.arange(1,13).reshape(2,6) #row*column must be equal to no of element in array/matrix
print(f)


f.resize(3,4)        # to modify the shape of original array     
print(f)
# f.reshape(3,4)      # it returns array but not modify original array
# print(f)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
# Missing Data
a = np.array([15, 10, np.nan, 3, 2, 5, 6, 4])
a
print(a.sum()) #results nan
# to ignore missing data while operating
print(np.nansum(a))
# # np.nanmean(a)
print(np.isnan(a))
print(np.where(np.isnan(a)))

nan
45.0
[False False  True False False False False False]
(array([2], dtype=int64),)


In [11]:
#2D arrays
g = np.array([(10,20,30),(40,50,60)])
#Alternatively
g = np.array([[10,20,30],[40,50,60]])
print(g)
print(g.ndim)     #dimension
print(g.size)     #Total Elements
print(g.shape)    #order

[[10 20 30]
 [40 50 60]]
2
6
(2, 3)


In [12]:
# Creating some usual matrices 
a=np.zeros((2,4)) ##Alternatively
# a = np.zeros([2,4],dtype=np.int16)
a 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a = np.ones([2,4],dtype=np.int16)
a 

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [46]:
# Any other number
print(np.full((2,2), 99))
print(np.full((5,5),np.nan))

[[99 99]
 [99 99]]
[[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]


In [15]:
# Random decimal numbers
np.random.rand(4,3)

array([[0.16118206, 0.52269961, 0.79602478],
       [0.80320518, 0.56826197, 0.16937888],
       [0.67583248, 0.54071804, 0.32590031],
       [0.26868209, 0.82675137, 0.93178696]])

In [16]:
# To get a matrix of all random numbers from 
i= np.empty((3,4),dtype=np.int16) # try with dtype=float16
print(i)
# To create a matrix of unity
print(np.ones([3,3]))     
# To create a diagonal matrix 
print(np.diag([14,15,16,17,18]))

[[10  0 20  0]
 [30  0 40  0]
 [50  0 60  0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[14  0  0  0  0]
 [ 0 15  0  0  0]
 [ 0  0 16  0  0]
 [ 0  0  0 17  0]
 [ 0  0  0  0 18]]


In [17]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 7,  4,  7],
       [ 6, -4,  0],
       [ 3,  4,  2]])

In [18]:
# The identity matrix
np.identity(5)   #OR
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:

a = np.array([[1,2,3]])
b = np.repeat(a,3, axis=0)      # Repeat an array
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
a = np.array([[10,20,30],[40,50,60]])
a
print(a.ravel())         # To get a flattened 1D array

print(a.reshape(3,2))        # returns the array with a modified shape
a
print(a.shape)

print(a.resize((3,2)))       #  resize( ) will modify the shape in the original array
a

[10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]
(2, 3)
None


array([[10, 20],
       [30, 40],
       [50, 60]])

In [21]:
# create some arrays A,b and B
A = np.array([[2,0,1],[4,3,8],[7,6,9]])
b = np.array([1,101,14])
B = np.array([[10,20,30],[40,50,60],[70,80,90]])
B
# #transpose
A
A.T
#A.transpose()  ##Alternatively
# # trace : sum along diagonal
np.trace(A)
# #Inverse
np.linalg.inv(A)

array([[ 0.53846154, -0.15384615,  0.07692308],
       [-0.51282051, -0.28205128,  0.30769231],
       [-0.07692308,  0.30769231, -0.15384615]])

In [22]:
print(A)
print(B)

# Matrix addition and subtraction
print(A+B)
print(A-B)

# Matrix multiplication
print(A.dot(B))     #OR
print(A @ B)

[[2 0 1]
 [4 3 8]
 [7 6 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[12 20 31]
 [44 53 68]
 [77 86 99]]
[[ -8 -20 -29]
 [-36 -47 -52]
 [-63 -74 -81]]
[[  90  120  150]
 [ 720  870 1020]
 [ 940 1160 1380]]
[[  90  120  150]
 [ 720  870 1020]
 [ 940 1160 1380]]


In [23]:
# other operations

np.absolute(B)
np.sqrt(B)
np.exp(B)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

In [24]:
A = np.arange(1,10).reshape(3,3)
print(A)

print(A.sum())
print(A.min())
print(A.max())
print(A.mean())
print(A.std()) #Standard deviation
print(A.var())  #variance

# to obtain the index of the minimum and maximum elements
A.argmin()
A.argmax()


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
1
9
5.0
2.581988897471611
6.666666666666667


8

In [25]:
# find the above statistics for each row or column
A
A.sum(axis=0)  #Each column Sum            
A.mean(axis = 0) 
A.std(axis = 0)
A.argmin(axis = 0)
A.min(axis=1)
A.argmax(axis = 1)
# find the cumulative sum along each row
A.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [26]:
# Indexing in arrays
x = np.arange(10)
x
x[2]
x[2:5]

array([2, 3, 4])

In [27]:
# Find out position of elements that satisfy a given condition
a = np.array([8, 3, 7, 0, 4, 2, 5, 2])
np.where(a > 4)

(array([0, 2, 6], dtype=int64),)

In [28]:
# Indexing with Arrays of Indices
x = np.arange(11,35,2)                    
print(x)
# array i which subsets the elements of x by taking assigned indices
i = np.array( [0,1,5,3,7,9 ] )
print(x[i])

[11 13 15 17 19 21 23 25 27 29 31 33]
[11 13 21 17 25 29]


In [29]:
# array i which subsets the elements of x
i = np.array( [0,1,5,3,7,9 ] )
print(x[i]) 

[11 13 21 17 25 29]


In [30]:
# create a 2D array j of indices to subset x.
j = np.array( [ [ 0, 1], [ 6, 2 ] ] )    
print(j,"\n",x[j]) 

[[0 1]
 [6 2]] 
 [[11 13]
 [23 15]]


In [31]:
# indexing with Boolean arrays
a = np.arange(12).reshape(3,4)
print(a)
b = a > 4
b     
# Note that 'b' is a Boolean with same shape as that of 'a'.
# 0 select the elements from 'a' which adhere to condition 'b'
a[b]   
a[b] = 12   
a 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4, 12, 12, 12],
       [12, 12, 12, 12]])

Mathematics

In [32]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [33]:
a + 2
a - 2
a * 2
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [35]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [36]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [37]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [38]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [39]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Reorganizing Arrays

In [40]:
import numpy as np
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1
h2
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous


Load Data from File

In [42]:
filedata = np.genfromtxt('/data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

OSError: /data.txt not found.

In [ ]:
dir(np)